language: java
sudo: false
before_install:
 - chmod +x gradlew
 - sleep 1m
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
script: gradle clean build check test
notifications:
  slack: scrummojito:MjnMALRNtGdBC9JhXUTx4D1o
