language: java
before_install:
 - chmod +x gradlew
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
script: gradle check
notifications:
  slack: scrummojito:MjnMALRNtGdBC9JhXUTx4D1o
