FORMAT: 1A
HOST: https://studyfindr.herokuapp.com

# ScrumMojito

ScrumMojito is a simple API allowing students to find matches.

## Facebook Authentication [/auth/facebook]

### Login to Facebook profile [GET /auth/facebook{?code}]

Login to a Facebook profile with the authentication code from Facebook.
The server will process this and gets the information from your profile (on first login).

+ Parameters
    + code (string, required) - Authentication Code from Facebook

+ Response 200 (application/json)

    + Body

            {
                "AccessToken": "testAccessToken",
                "id": 10123456789
            }

    + Schema
    
            {
                "AccessToken": {
                    "type": "string"
                },
                "id": {
                    "type": "long"
                }
            }

### Logout from Facebook profile [GET /auth/facebook/logout{?accessToken,id}]

Logout from the current Facebook profile.

+ Parameters
    + accessToken (string, required) - Access Code from Facebook
    + id (long, required) - User Facebook id

+ Response 200 (application/json)
    
    + Body
        
            {
                "message": "Succesfully logged out"
            }
        
    + Schema
    
            {
                "message": {
                    "type": "string"
                    }
            }

## School [/school]

### Get schools [GET /school{?name}]

Get all schools or the school with a given name.

+ Parameters
    + name (string) - Name of the required school (if NULL, all schools get returned)
    
+ Response 200 (application/json)

    + Body
    
            {
                {
                    "id": 1,
                    "name": "Technologiecampus Odisee",
                    "address": "Gebroeders De Smedtstraat 1, 9000 Gent"
                },
                {
                    "id": 2,
                    "name": "HoGent",
                    "address": "Valentin Vaerwyckweg, 9000 Gent"
                }
            }
            
    + Schema
    
            {
                {
                    "id": {
                        "type": "int"
                        },
                    "name": {
                        "type": "string"
                        },
                    "address" : {
                        "type": "string"
                        }
                }
            }
            
## User [/user]

### Get info [GET /user/{?id}/info]

Get the info about the user with the given id.

+ Parameters
    + id (long, required) - Access Code from Facebook

+ Response 200 (application/json)

    + Body
    
            {
                "id": "10123456789",
                "email": "test@gmail.com",
                "firstname": "Jos",
                "lastname": "De Bakker",
                "location": "Gent",
                "age": 20,
                "prefMale": false,
                "prefFemale": true,
                "prefTrans": false,
                "prefAge": 20,
                "prefDistance": 25,
                "prefLocation": 1
            }
            
    + Schema
    
            {
                "id": {
                    "type": "int"
                    },
                
                
            }